---
title: "Maps"
author: "Yanyu Zheng yz2690"
date: "February 18, 2016"
output: html_document
---
# Data Cleaning & Basic Setup
```{r}
# Set working directory & Load in functions
setwd("~/Data Science/project2-project2-group2/data")
x = c("leaflet","dplyr","data.table","XML")
source("../lib/drawMap.R")
source("../lib/getGps.R")
source("../lib/getDataGps.R")
#install.packages(x)
lapply(x,library,character.only = TRUE)

## Data cleaning for mice data
colsToKeep = c("Created Date","Incident Zip","Latitude","Longitude")
miceData = fread("Rat_Sightings.csv",select = colsToKeep)
colnames(miceData) = c("Date","Zip","Latitude","Longitude")
miceData = miceData %>% 
  na.omit() %>%
  mutate(Date = as.Date(Date,"%m/%d/%Y"), Zip = as.numeric(Zip))
save(miceData, file = "miceData.RData") 
rm(miceData)

## Data cleaning for retaurant data
colsToKeep = c("DBA","STREET","BORO","CUISINE DESCRIPTION","ZIPCODE","SCORE")
resData = fread("restaurant.csv",select = colsToKeep)
resDataColumbia = resData %>%
  na.omit() %>%
  mutate(addr = paste(DBA, STREET, BORO, sep = ",")) %>%
  unique(by = "DBA") %>%
  filter(ZIPCODE >= 10024 & ZIPCODE <=10028)
save(resDataColumbia, file = "miceDataColumbia.RData")
gps = lapply(resDataColumbia$addr,getGps)
gps = do.call(rbind,gps)
for(i in 1:nrow(data)){
  gps = getGps(resData[i,addr])
  Longtitude = c(Longtitude,gps[1])
  Latitude = c(Latitude,gps[2])
}
#19866
resData = cbind(resData,Longtitude,Latitude)
```
# Basic set up
```{r}
setwd("~/Data Science/project2-project2-group2/data")
load("miceData.RData")

#'
#'@Date Created Date of the incident report
#'@Zip  Zip code of incident
#'@Latitude    Latitude of incident
#'@Longitude   Longitude coordinate of incident
#'
```
# Basic mice distribution
```{r}
samp = sample_n(miceData,7000)
mSamp = drawMap(samp)
mSamp
mSampCluster = drawMapCluster(samp)
mSampCluster
```
# Top Five mice area
```{r}
topTen = miceData %>%
  group_by(Zip) %>%
  filter("2010-01-01"<=Date & "2011-01-01">=Date) %>%
  summarise(miceNum = n()) %>%
  arrange(desc(miceNum))
topFiveData = miceData %>%
  filter(Zip %in% topFive$Zip[1:5])
mTopFive = drawMap(topFiveData)
mTopFive
```
# Mice by zip code & time
```{r}
zipToKeep = c(10027,10026,10025)
timeRange = c("2015-12-25","2016-02-14")
filtData = miceData %>%
  filter(Zip %in% zipToKeep) %>%
  filter(Date >= timeRange[1] & Date <= timeRange[2])
mFiltData = drawMap(filtData) 
```
# Mice by season
```{r}

```


